name: 🐛 Bug Report
description: Report a bug in the Boombox Design System
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - "@boombox/components"
        - "@boombox/tokens"
        - "@boombox/icons"
        - "@boombox/utils"
        - "@boombox/email"
        - "Documentation/Storybook"
        - "Not sure"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you using?
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile Safari
        - Mobile Chrome

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment details
      value: |
        - OS: [e.g. iOS, Windows, macOS]
        - Node version: [e.g. 18.x]
        - Package manager: [e.g. npm, yarn, pnpm]
        - Framework: [e.g. React, Next.js]
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. 