name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issues:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to author
        if: github.event_name == 'pull_request'
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          
      - name: Auto-assign reviewers
        if: github.event_name == 'pull_request'
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto-assign.yml'

  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label PR
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add triage label to issues
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['triage']
            }); 