name: Auto Assign

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to author
        if: github.event_name == 'pull_request'
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          
      - name: Auto-assign reviewers
        if: github.event_name == 'pull_request'
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto-assign.yml'

  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Label based on file changes
        if: github.event_name == 'pull_request'
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yml'

      - name: Add triage label to issues
        if: github.event_name == 'issues'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['triage']
            }); 